import Head from "next/head";
import Image from "next/image";

import countries from "../countries.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Where in the world?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
