import Head from "next/head";
import { useTheme } from "next-themes";

import CountryCard from "../components/CountryCard.js";
import { countries } from "../countries.js";

export default function Home({ countriesList }) {
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Where in the world?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-8 mx-6">
        <div className="flex flex-wrap justify-center gap-12">
          {countriesList.map((country) => {
            return <CountryCard key={country.name} country={country} />;
          })}
        </div>
      </div>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      countriesList: countries,
    },
  };
}
