import Head from "next/head";

import CountryCard from "../components/CountryCard.js";
import NavBar from "../components/NavBar.js";
import { useTheme } from "next-themes";
import { countries } from "../countries.js";

export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <div className="bg-white dark:bg-veryDarkBlue w-screen h-screen overflow-x-hidden">
      <Head>
        <title>Where in the world?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className="mt-8 mx-6">
        <div className="flex flex-wrap justify-center gap-12">
          {countries.map((country) => {
            return <CountryCard key={country.name} country={country} />;
          })}
        </div>
      </div>
    </div>
  );
}
